### ISSUE TITLE
Skipping LoL Launcher before DIM fully injects leads to Dargon-less game

### ISSUE THREAD

**Issue by miyu** [the-dargon-project/the-dargon-project#17]
This is equivalent to starting Dargon while the launcher is running - it will ignore the LoL air client's launching because it hasn't hooked the launcher process (and thus doesn't care about the processor tree). 

A few solutions come to mind, which I'll outline below.

Launcher already running case:
- Hide the launcher window, notify user we're getting things setup and inject, show the launcher window (Might be a bit wonky implementation-wise - now we have multiple codepaths to start DIM...
- Screenshot the launcher window, replace the launcher window with a decoy and kill the launcher, start a new launcher, use normal code path.
- Notify user and have them kill the launcher for us. or overlay the window with a "Restart with Dargon" button and when clicked, do it for them, else abandon the process tree.
- Just inject and cross your fingers.

Didn't inject fast enough case:
- Inject into AIR Client anyway (currently happens)
- Kill the air client and launcher, say for technical reasons that aren't bad we need the user to go more slowly.
- Fail silently / notification tray popup (do those still exist? Nobody uses that anymore because it's annoying)

**Comment by RichieSams** [comment]
I vote for hiding the window as soon as it's created. Then, reshowing after
hook. That way, we can delay as long as needed
