### ISSUE TITLE
trinket-dim should use feature toggle to determine if console window shows.

### ISSUE THREAD

**Issue by miyu** [the-dargon-project/the-dargon-project#27]
Ideas: Leverage registry or some file located in dargon directory to determine if we should show the console window. Obviously default to not showing console window for most users.

**Comment by RichieSams** [comment]
An ini "settings" file would work

**Comment by miyu** [comment]
Now using feature toggle `enable-trinket-dim-console` - We can consider ini files if we ever need something more complicated.
